# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Build Project

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create custom Maven Settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: custom_maven_settings.xml
          servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
      - name: Build Native with Maven
        if: ${{ github.event_name == 'pull_request' }}
        run: ./mvnw -s custom_maven_settings.xml -B -Pnative clean verify
      - name: Build with Maven
        if: ${{ github.event_name == 'push' }}
        run: ./mvnw -s custom_maven_settings.xml -B clean verify
